import 'package:test/test.dart';

import '../tool/candidate_consumer.dart';
import '../tool/repo_tasks.dart';

void main() {
  final RepoWorkspace workspace = RepoWorkspace.discover('.');
  const String repository = 'ssh://git@example.invalid/example/patchbay.git';
  const String commit = '0123456789abcdef0123456789abcdef01234567';

  test('候选 overrides 从 workspace 生成四包同源固定提交', () {
    final String yaml = renderCandidateOverrides(
      workspace.members,
      repository: repository,
      commit: commit,
    );

    for (final RepoPackage package in workspace.members) {
      expect(yaml, contains('  ${package.name}:'));
      expect(yaml, contains("      path: '${package.path}'"));
    }
    expect("url: '$repository'".allMatches(yaml), hasLength(4));
    expect("ref: '$commit'".allMatches(yaml), hasLength(4));
    expect(yaml, contains('不要提交到 consumer 仓库'));
  });

  test('候选参数只接受完整提交 SHA，不接受移动分支', () {
    expect(
      () => CandidateConsumerOptions.parse(<String>[
        '--repository',
        repository,
        '--commit',
        'dev/0.6.0',
      ]),
      throwsA(
        isA<FormatException>().having(
          (FormatException error) => error.message,
          'message',
          contains('完整的 40 位 commit SHA'),
        ),
      ),
    );
  });

  test('候选生成与 lock 验证模式必须二选一', () {
    expect(
      CandidateConsumerOptions.parse(<String>[
        '--repository',
        repository,
        '--commit',
        commit,
        '--output',
        '/tmp/pubspec_overrides.yaml',
      ]).output,
      '/tmp/pubspec_overrides.yaml',
    );
    expect(
      () => CandidateConsumerOptions.parse(<String>[
        '--repository',
        repository,
        '--commit',
        commit,
      ]),
      throwsA(
        isA<FormatException>().having(
          (FormatException error) => error.message,
          'message',
          contains('必须二选一'),
        ),
      ),
    );
  });

  test('lock 验证要求四包都命中相同 git URL、提交和仓内路径', () {
    final String lock = _candidateLock(
      workspace.members,
      repository: repository,
      commit: commit,
    );

    expect(
      verifyCandidateLock(
        lock,
        workspace.members,
        repository: repository,
        commit: commit,
      ),
      isEmpty,
    );

    expect(
      verifyCandidateLock(
        lock.replaceFirst('resolved-ref: "$commit"', 'resolved-ref: "bad"'),
        workspace.members,
        repository: repository,
        commit: commit,
      ).single,
      contains('resolved-ref'),
    );
  });

  test('repo task 暴露 candidate-consumer 并原样转发参数', () {
    final RepoTaskCatalog catalog = RepoTaskCatalog(workspace);
    final List<RepoCommand> commands = catalog.commandsFor(
      'candidate-consumer',
      taskArguments: <String>['--repository', repository, '--commit', commit],
    );

    expect(commands, hasLength(1));
    expect(commands.single.arguments, <String>[
      'run',
      'tool/candidate_consumer.dart',
      '--repository',
      repository,
      '--commit',
      commit,
    ]);
  });
}

String _candidateLock(
  Iterable<RepoPackage> packages, {
  required String repository,
  required String commit,
}) {
  final StringBuffer out = StringBuffer()
    ..writeln('# Generated by pub')
    ..writeln('packages:');
  for (final RepoPackage package in packages) {
    out
      ..writeln('  ${package.name}:')
      ..writeln('    dependency: "direct overridden"')
      ..writeln('    description:')
      ..writeln('      path: "${package.path}"')
      ..writeln('      ref: "$commit"')
      ..writeln('      resolved-ref: "$commit"')
      ..writeln('      url: "$repository"')
      ..writeln('    source: git')
      ..writeln('    version: "0.5.0"');
  }
  out
    ..writeln('sdks:')
    ..writeln('  dart: ">=3.12.0 <4.0.0"');
  return out.toString();
}
