import 'package:test/test.dart';

import '../../tool/release_prep.dart';
import '../fixture/release_prep_fixtures.dart';

void main() {
  group('example/pubspec.lock', () {
    const String lock = '''
# Generated by pub
packages:
  args:
    dependency: transitive
    description:
      name: args
      sha256: "abc"
      url: "https://pub.dev"
    source: hosted
    version: "2.7.0"
  patchbay:
    dependency: transitive
    description:
      path: "../../patchbay"
      relative: true
    source: path
    version: "0.2.1"
  patchbay_flutter:
    dependency: "direct main"
    description:
      path: ".."
      relative: true
    source: path
    version: "0.2.1"
sdks:
  dart: ">=3.11.0 <4.0.0"
''';

    test('只读 path 源的随版包版本', () {
      expect(readLockPathVersions(lock), <String, String>{
        'patchbay': '0.2.1',
        'patchbay_flutter': '0.2.1',
      });
    });

    test('刷版本只动这些格子，hosted 条目零漂移，且幂等', () {
      final String applied = applyLockVersions(lock, '0.3.0');
      expect(readLockPathVersions(applied), <String, String>{
        'patchbay': '0.3.0',
        'patchbay_flutter': '0.3.0',
      });
      expect(applied, contains('    version: "2.7.0"'));
      expect(applied, contains('  dart: ">=3.11.0 <4.0.0"'));
      expect(applyLockVersions(applied, '0.3.0'), applied);
    });
  });

  group('兼容矩阵', () {
    const String matrix = '''
# 兼容性矩阵

## 当前记录

| patchbay tag | commit SHA | wire schemaVersion | Flutter（CI 验证） | Flutter（文档最低支持） | 已知 consumer |
|---|---|---|---|---|---|
| `patchbay-v0.2.1` | `d32f45e9d652920902e51f9c3dc25c189d804e46` | 1 | 3.44.9 | `>=3.38.0` | 内部接入方 ×2 |

字段来源：
''';

    test('表头与分隔行不会被当成数据行', () {
      final List<CompatRow> rows = parseCompatRows(matrix);
      expect(rows, hasLength(1));
      expect(rows.single.tag, 'patchbay-v0.2.1');
      expect(rows.single.commitSha, 'd32f45e9d652920902e51f9c3dc25c189d804e46');
      expect(rows.single.schemaVersion, '1');
      expect(rows.single.flutterMin, '>=3.38.0');
      expect(rows.single.hasPending, isFalse);
    });

    test('新行插到表顶，旧行不动', () {
      const CompatRow row = CompatRow(
        tag: 'patchbay-v0.3.0',
        commitSha: pendingSha,
        schemaVersion: '1',
        flutterCi: '3.44.9',
        flutterMin: '>=3.38.0',
        consumers: pendingConsumers,
      );
      final String applied = applyCompatMatrixRow(matrix, row);
      final List<CompatRow> rows = parseCompatRows(applied);
      expect(rows.map((r) => r.tag), <String>[
        'patchbay-v0.3.0',
        'patchbay-v0.2.1',
      ]);
      expect(rows.first.hasPending, isTrue);
    });

    test('同 tag 行已存在时不覆盖——人工回填过的内容不被脚本推平', () {
      const CompatRow row = CompatRow(
        tag: 'patchbay-v0.2.1',
        commitSha: pendingSha,
        schemaVersion: '9',
        flutterCi: '0.0.0',
        flutterMin: '>=0.0.0',
        consumers: pendingConsumers,
      );
      expect(applyCompatMatrixRow(matrix, row), matrix);
    });

    test('渲染体例与现表一致', () {
      const CompatRow row = CompatRow(
        tag: 'patchbay-v0.3.0',
        commitSha: 'abc',
        schemaVersion: '1',
        flutterCi: '3.44.9',
        flutterMin: '>=3.38.0',
        consumers: '待确认',
      );
      expect(
        row.render(),
        '| `patchbay-v0.3.0` | `abc` | 1 | 3.44.9 | `>=3.38.0` | 待确认 |',
      );
    });
  });

  group('源码取值', () {
    test('schemaVersion 与 CI Flutter 版本从真源读出', () {
      expect(readSchemaVersion('  static const int schemaVersion = 3;'), 3);
      expect(readSchemaVersion('无常量'), isNull);
      expect(
        readCiFlutterVersion("env:\n  FLUTTER_VERSION: '3.44.9'\n"),
        '3.44.9',
      );
    });
  });

  group('判定', () {
    test('未 bump / 未落款 / lock 未刷 / 缺矩阵行——四件套全红', () {
      final List<ReleaseCheck> checks = evaluateRelease(
        version: '0.3.0',
        inputs: releaseInputsFixture(),
        resolveTag: (_) => null,
      );
      expect(statusOf(checks, 'version-parity'), ReleaseCheckStatus.failed);
      expect(statusOf(checks, 'changelog-release'), ReleaseCheckStatus.failed);
      expect(statusOf(checks, 'example-lock'), ReleaseCheckStatus.failed);
      expect(statusOf(checks, 'compat-matrix-row'), ReleaseCheckStatus.failed);
    });

    test('0.2.0 / 0.2.1 漏过的两项是硬检查', () {
      final List<ReleaseCheck> checks = evaluateRelease(
        version: '0.3.0',
        inputs: releaseInputsFixture(),
        resolveTag: (_) => null,
      );
      expect(checkOf(checks, 'example-lock').hard, isTrue);
      expect(checkOf(checks, 'compat-matrix-row').hard, isTrue);
      expect(checkOf(checks, 'compat-matrix-backfill').hard, isTrue);
      expect(checkOf(checks, 'publish-manifest').hard, isTrue);
      expect(checkOf(checks, 'package-changelog').hard, isTrue);
      expect(checkOf(checks, 'internal-dep-constraints').hard, isTrue);
      expect(checkOf(checks, 'workspace-resolution').hard, isTrue);
      expect(checkOf(checks, 'documentation-current').hard, isTrue);
    });

    group('当前文档治理', () {
      test('hosted 安装、双语入口、SVG 与中性示例齐全时通过', () {
        final ReleaseCheck check = checkOf(
          evaluateRelease(
            version: '0.3.0',
            inputs: releaseInputsFixture(released: true),
            resolveTag: (_) => null,
          ),
          'documentation-current',
        );
        expect(check.status, ReleaseCheckStatus.ok);
        expect(check.hard, isTrue);
      });

      test('旧版安装口径与未发布措辞会阻断', () {
        final ReleaseCheck check = checkOf(
          evaluateRelease(
            version: '0.3.0',
            inputs: releaseInputsFixture(
              released: true,
              documentOverrides: <String, String>{
                'docs/guide.md':
                    releaseDocumentsFixture('0.2.1')['docs/guide.md']!
                        .replaceFirst('# Guide', '# Guide\n\n尚未发布到 pub.dev'),
              },
            ),
            resolveTag: (_) => null,
          ),
          'documentation-current',
        );
        expect(check.status, ReleaseCheckStatus.failed);
        expect(check.detail, contains('尚未发布到 pub.dev'));
        expect(check.detail, contains('patchbay-v0.2.1'));
      });

      test('定版前提前宣称已发布会阻断', () {
        final Map<String, String> documents = releaseDocumentsFixture('0.3.0');
        final ReleaseCheck check = checkOf(
          evaluateRelease(
            version: '0.3.0',
            inputs: releaseInputsFixture(
              released: true,
              documentOverrides: <String, String>{
                'README.md':
                    '${documents['README.md']}\npublished on pub.dev\n',
                'README.zh-CN.md':
                    '${documents['README.zh-CN.md']}\n已发布到 pub.dev\n',
              },
            ),
            resolveTag: (_) => null,
          ),
          'documentation-current',
        );
        expect(check.status, ReleaseCheckStatus.failed);
        expect(check.detail, contains('published on pub.dev'));
        expect(check.detail, contains('已发布到 pub.dev'));
      });

      test('业务命令泄漏与架构 SVG 能力缺失会阻断', () {
        final Map<String, String> documents = releaseDocumentsFixture('0.3.0');
        final ReleaseCheck check = checkOf(
          evaluateRelease(
            version: '0.3.0',
            inputs: releaseInputsFixture(
              released: true,
              documentOverrides: <String, String>{
                'docs/design.md': documents['docs/design.md']!.replaceFirst(
                  'example.job.run',
                  'consumer.device.pair',
                ),
                'docs/assets/patchbay-architecture.svg':
                    documents['docs/assets/patchbay-architecture.svg']!
                        .replaceFirst('gesture / inspect / wait', 'navigation'),
              },
            ),
            resolveTag: (_) => null,
          ),
          'documentation-current',
        );
        expect(check.status, ReleaseCheckStatus.failed);
        expect(check.detail, contains('非中性命令示例'));
        expect(check.detail, contains('gesture / inspect / wait'));
      });

      test('工作流 SVG、稳定概念和各入口引用漂移会阻断', () {
        final Map<String, String> documents = releaseDocumentsFixture('0.3.0');
        final ReleaseCheck check = checkOf(
          evaluateRelease(
            version: '0.3.0',
            inputs: releaseInputsFixture(
              released: true,
              documentOverrides: <String, String>{
                'README.zh-CN.md': documents['README.zh-CN.md']!.replaceFirst(
                  '<img src="docs/assets/patchbay-cli-workflows.svg">',
                  '',
                ),
                'docs/assets/patchbay-cli-workflows.svg':
                    documents['docs/assets/patchbay-cli-workflows.svg']!
                        .replaceFirst('APP KEEPS RUNNING', 'APP'),
              },
            ),
            resolveTag: (_) => null,
          ),
          'documentation-current',
        );
        expect(check.status, ReleaseCheckStatus.failed);
        expect(check.detail, contains('README.zh-CN.md'));
        expect(check.detail, contains('APP KEEPS RUNNING'));
      });
    });

    test('四件套补齐后转绿', () {
      final List<ReleaseCheck> checks = evaluateRelease(
        version: '0.3.0',
        inputs: releaseInputsFixture(released: true),
        resolveTag: (_) => null,
      );
      for (final String id in <String>[
        'version-parity',
        'schema-version-parity',
        'changelog-release',
        'package-changelog',
        'example-lock',
        'compat-matrix-row',
      ]) {
        expect(statusOf(checks, id), ReleaseCheckStatus.ok, reason: id);
      }
    });

    test('包内 CHANGELOG 没提当前版本就红——pub 会因此退 65', () {
      final ReleaseCheck check = checkOf(
        evaluateRelease(
          version: '0.3.0',
          inputs: releaseInputsFixture(
            released: true,
            packageChangelogVersion: '0.2.1',
          ),
          resolveTag: (_) => null,
        ),
        'package-changelog',
      );
      expect(check.status, ReleaseCheckStatus.failed);
      expect(check.detail, contains('未记 0.3.0'));
    });

    test('schemaVersion 两处不一致直接红', () {
      final List<ReleaseCheck> checks = evaluateRelease(
        version: '0.3.0',
        inputs: releaseInputsFixture(released: true, invocationSchema: 2),
        resolveTag: (_) => null,
      );
      expect(
        statusOf(checks, 'schema-version-parity'),
        ReleaseCheckStatus.failed,
      );
    });

    test('矩阵行的 schemaVersion 与源码漂移时红', () {
      final List<ReleaseCheck> checks = evaluateRelease(
        version: '0.3.0',
        inputs: releaseInputsFixture(released: true, matrixSchemaCell: '2'),
        resolveTag: (_) => null,
      );
      expect(statusOf(checks, 'compat-matrix-row'), ReleaseCheckStatus.failed);
    });

    group('tag 后回填', () {
      test('tag 已存在但格子还是占位符——0.2.1 漏的那一步会红', () {
        final List<ReleaseCheck> checks = evaluateRelease(
          version: '0.3.0',
          inputs: releaseInputsFixture(released: true),
          resolveTag: (tag) => tag == 'patchbay-v0.3.0' ? fixtureSha : null,
        );
        final ReleaseCheck backfill = checkOf(checks, 'compat-matrix-backfill');
        expect(backfill.status, ReleaseCheckStatus.failed);
        expect(backfill.detail, contains('占位符'));
      });

      test('回填成 peeled SHA 后转绿', () {
        final List<ReleaseCheck> checks = evaluateRelease(
          version: '0.3.0',
          inputs: releaseInputsFixture(
            released: true,
            sha: fixtureSha,
            consumers: '内部接入方 ×2',
          ),
          resolveTag: (tag) => tag == 'patchbay-v0.3.0' ? fixtureSha : null,
        );
        expect(
          statusOf(checks, 'compat-matrix-backfill'),
          ReleaseCheckStatus.ok,
        );
      });

      test('填错 SHA 也红', () {
        final List<ReleaseCheck> checks = evaluateRelease(
          version: '0.3.0',
          inputs: releaseInputsFixture(
            released: true,
            sha: 'f' * 40,
            consumers: '内部接入方 ×2',
          ),
          resolveTag: (tag) => tag == 'patchbay-v0.3.0' ? fixtureSha : null,
        );
        final ReleaseCheck backfill = checkOf(checks, 'compat-matrix-backfill');
        expect(backfill.status, ReleaseCheckStatus.failed);
        expect(backfill.detail, contains('实际 peeled SHA'));
      });

      test('tag 解析不出时跳过，不误判成红', () {
        final List<ReleaseCheck> checks = evaluateRelease(
          version: '0.3.0',
          inputs: releaseInputsFixture(released: true),
          resolveTag: (_) => null,
        );
        expect(
          statusOf(checks, 'compat-matrix-backfill'),
          ReleaseCheckStatus.skipped,
        );
      });
    });

    group('pub 发布门', () {
      test('path 依赖 / 缺 LICENSE 是硬红', () {
        final ReleaseCheck manifest = checkOf(
          evaluateRelease(
            version: '0.3.0',
            inputs: releaseInputsFixture(released: true),
            resolveTag: (_) => null,
          ),
          'publish-manifest',
        );
        expect(manifest.status, ReleaseCheckStatus.failed);
        expect(manifest.detail, contains('path 依赖'));
        expect(manifest.detail, contains('缺 LICENSE'));
      });

      test('发布开关单列一项，措辞说明它由仓主翻', () {
        final ReleaseCheck off = checkOf(
          evaluateRelease(
            version: '0.3.0',
            inputs: releaseInputsFixture(released: true),
            resolveTag: (_) => null,
          ),
          'publish-switch',
        );
        expect(off.status, ReleaseCheckStatus.failed);
        expect(off.hard, isTrue);
        expect(off.detail, contains('publish_to: none'));
        expect(off.detail, contains('--enable-publish'));
        expect(
          checkOf(
            evaluateRelease(
              version: '0.3.0',
              inputs: releaseInputsFixture(released: true),
              resolveTag: (_) => null,
            ),
            'publish-manifest',
          ).detail,
          isNot(contains('publish_to')),
        );

        expect(
          statusOf(
            evaluateRelease(
              version: '0.3.0',
              inputs: releaseInputsFixture(released: true, publishable: true),
              resolveTag: (_) => null,
            ),
            'publish-switch',
          ),
          ReleaseCheckStatus.ok,
        );
      });

      test('删 publish_to 只动那一行，没有该行则原样', () {
        const String pubspec =
            'name: patchbay\nversion: 0.3.0\npublish_to: none\n\nenvironment:\n';
        final String enabled = applyRemovePublishTo(pubspec);
        expect(enabled, 'name: patchbay\nversion: 0.3.0\n\nenvironment:\n');
        expect(applyRemovePublishTo(enabled), enabled);
      });

      test('改成 hosted 约束并补齐包内文件后转绿', () {
        final List<ReleaseCheck> checks = evaluateRelease(
          version: '0.3.0',
          inputs: releaseInputsFixture(released: true, publishable: true),
          resolveTag: (_) => null,
        );
        for (final String id in <String>[
          'publish-manifest',
          'publish-advisories',
          'internal-dep-constraints',
          'workspace-resolution',
        ]) {
          expect(statusOf(checks, id), ReleaseCheckStatus.ok, reason: id);
        }
      });

      test('description 太短是 warning，一样挡发布', () {
        final ReleaseCheck advisories = checkOf(
          evaluateRelease(
            version: '0.3.0',
            inputs: releaseInputsFixture(
              released: true,
              publishable: true,
              description: '太短了。',
            ),
            resolveTag: (_) => null,
          ),
          'publish-advisories',
        );
        expect(advisories.status, ReleaseCheckStatus.failed);
        expect(advisories.detail, contains('description'));
        expect(advisories.hard, isTrue);
      });

      test('随版依赖约束停在旧版本时红', () {
        final ReleaseCheck check = checkOf(
          evaluateRelease(
            version: '0.4.0',
            inputs: releaseInputsFixture(
              released: true,
              publishable: true,
              version: '0.4.0',
              constraintVersion: '0.3.0',
            ),
            resolveTag: (_) => null,
          ),
          'internal-dep-constraints',
        );
        expect(check.status, ReleaseCheckStatus.failed);
        expect(check.detail, contains('不接纳 0.4.0'));
      });

      test('还是 path 依赖时该项跳过，交给 publish-manifest 说话', () {
        expect(
          statusOf(
            evaluateRelease(
              version: '0.3.0',
              inputs: releaseInputsFixture(released: true),
              resolveTag: (_) => null,
            ),
            'internal-dep-constraints',
          ),
          ReleaseCheckStatus.skipped,
        );
      });

      test('example override 指错路径或缺条目时红', () {
        final ReleaseCheck missing = checkOf(
          evaluateRelease(
            version: '0.3.0',
            inputs: releaseInputsFixture(
              released: true,
              publishable: true,
              dropOverrides: <String>{'example'},
            ),
            resolveTag: (_) => null,
          ),
          'workspace-resolution',
        );
        expect(missing.status, ReleaseCheckStatus.failed);
        expect(missing.detail, contains('缺 patchbay'));

        final ReleaseCheck wrong = checkOf(
          evaluateRelease(
            version: '0.3.0',
            inputs: releaseInputsFixture(
              released: true,
              publishable: true,
              exampleOverridePath: '../patchbay',
            ),
            resolveTag: (_) => null,
          ),
          'workspace-resolution',
        );
        expect(wrong.status, ReleaseCheckStatus.failed);
        expect(wrong.detail, contains('应为 ../../patchbay'));
      });

      test('排版门禁：有漂移即红，跑不起来才跳过', () {
        expect(evaluateFormatGate(0).status, ReleaseCheckStatus.ok);
        expect(evaluateFormatGate(1).status, ReleaseCheckStatus.failed);
        expect(evaluateFormatGate(null).status, ReleaseCheckStatus.skipped);
        expect(evaluateFormatGate(1).hard, isTrue);
      });

      test('dry-run 判定：有非零退出即红，静态门未过则跳过', () {
        expect(
          evaluatePublishDryRun(
            exitCodes: const <String, int>{'patchbay': 0, 'patchbay_cli': 65},
            skipped: const <String>[],
          ).status,
          ReleaseCheckStatus.failed,
        );
        expect(
          evaluatePublishDryRun(
            exitCodes: const <String, int>{'patchbay': 0},
            skipped: const <String>[],
          ).status,
          ReleaseCheckStatus.ok,
        );
        expect(
          evaluatePublishDryRun(
            exitCodes: const <String, int>{},
            skipped: const <String>['patchbay'],
          ).status,
          ReleaseCheckStatus.skipped,
        );
      });
    });

    test('版本号必须是 SemVer', () {
      expect(() => requireVersion('0.3'), throwsA(isA<FormatException>()));
      expect(() => requireVersion('v0.3.0'), throwsA(isA<FormatException>()));
      expect(requireVersion('0.3.0'), '0.3.0');
      expect(requireVersion('0.4.0-rc.1'), '0.4.0-rc.1');
    });
  });
}
